In [251]:
import pandas as pd
import numpy as np
from datetime import datetime
from sklearn.preprocessing import StandardScaler
from pathlib import Path

In [252]:
April_may_df = pd.read_csv('Classes April-May 2018.csv')
April_may_df.head()

,ActivitySiteID,ActivityDescription,BookingEndDateTime (Month / Day / Year),BookingStartTime,MaxBookees,Number Booked,Price (INR)
0,HXP,20-20-20 2.45pm-3.45pm,08-Apr-18,14:45:00,25,12,499.0
1,HXP,20-20-20 2.45pm-3.45pm,15-Apr-18,14:45:00,25,15,499.0
2,HXP,20-20-20 2.45pm-3.45pm,22-Apr-18,14:45:00,25,14,499.0
3,HXP,20-20-20 2.45pm-3.45pm,29-Apr-18,14:45:00,25,9,499.0
4,HXP,20-20-20 2.45pm-3.45pm,06-May-18,14:45:00,25,7,499.0

In [253]:
June_df =  pd.read_csv('Classes June 2018.csv')
June_df.head()

,ActivitySiteID,ActivityDescription,BookingEndDateTime (Month / Day / Year),BookingStartTime,MaxBookees,Number Booked,Price (INR)
0,BRP,20:20:20 9.30-10.30am,01-Jun-18,9:30:00,35,28,499
1,BRP,20:20:20 9.30-10.30am,08-Jun-18,9:30:00,35,35,499
2,BRP,20:20:20 9.30-10.30am,15-Jun-18,9:30:00,35,31,499
3,BRP,20:20:20 9.30-10.30am,22-Jun-18,9:30:00,35,32,499
4,BRP,20:20:20 9.30-10.30am,29-Jun-18,9:30:00,35,19,499

In [254]:
# checking null values
April_may_df.isnull().sum() / len(April_may_df)* 100

ActivitySiteID                             0.000000
ActivityDescription                        0.000000
BookingEndDateTime (Month / Day / Year)    0.000000
BookingStartTime                           0.000000
MaxBookees                                 0.000000
Number Booked                              0.000000
Price (INR)                                0.826826
dtype: float64

In [255]:
# checking null values for june data
June_df.isnull().sum() / len(April_may_df)* 100

ActivitySiteID                             0.0
ActivityDescription                        0.0
BookingEndDateTime (Month / Day / Year)    0.0
BookingStartTime                           0.0
MaxBookees                                 0.0
Number Booked                              0.0
Price (INR)                                0.0
dtype: float64

In [256]:
# dropping null values as it has no price mentioned in it
df1 = April_may_df.dropna()
df2 = June_df.dropna()

In [257]:
df1.drop_duplicates()
df2.drop_duplicates()

,ActivitySiteID,ActivityDescription,BookingEndDateTime (Month / Day / Year),BookingStartTime,MaxBookees,Number Booked,Price (INR)
0,BRP,20:20:20 9.30-10.30am,01-Jun-18,9:30:00,35,28,499
1,BRP,20:20:20 9.30-10.30am,08-Jun-18,9:30:00,35,35,499
2,BRP,20:20:20 9.30-10.30am,15-Jun-18,9:30:00,35,31,499
3,BRP,20:20:20 9.30-10.30am,22-Jun-18,9:30:00,35,32,499
4,BRP,20:20:20 9.30-10.30am,29-Jun-18,9:30:00,35,19,499
...,...,...,...,...,...,...,...
1107,TSC,Zumba 6.30-7.30pm,18-Jun-18,18:30:00,18,9,1299
1108,TSC,Zumba 6.30-7.30pm,25-Jun-18,18:30:00,18,9,1299
1109,TSC,Zumba - 6-7pm,07-Jun-18,18:00:00,50,16,1299
1110,TSC,Zumba - 6-7pm,14-Jun-18,18:00:00,50,13,1299
1111,TSC,Zumba - 6-7pm,21-Jun-18,18:00:00,50,12,1299

In [258]:
df1 = df1.rename(columns={'BookingEndDateTime (Month / Day / Year)': 'BookingEndDateTime', 'Price (INR)' : 'PriceINR'})
df2 = df2.rename(columns={'BookingEndDateTime (Month / Day / Year)': 'BookingEndDateTime', 'Price (INR)' : 'PriceINR'})

In [259]:
df1['BookingEndDateTime'] = pd.to_datetime(df1['BookingEndDateTime'])
df2['BookingEndDateTime'] = pd.to_datetime(df2['BookingEndDateTime'])

/tmp/ipython-input-2177272147.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df1['BookingEndDateTime'] = pd.to_datetime(df1['BookingEndDateTime'])
/tmp/ipython-input-2177272147.py:2: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df2['BookingEndDateTime'] = pd.to_datetime(df2['BookingEndDateTime'])

In [260]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2159 entries, 0 to 2176
Data columns (total 7 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   ActivitySiteID       2159 non-null   object
 1   ActivityDescription  2159 non-null   object
 2   BookingEndDateTime   2159 non-null   datetime64[ns]
 3   BookingStartTime     2159 non-null   object
 4   MaxBookees           2159 non-null   int64
 5   Number Booked        2159 non-null   int64
 6   PriceINR             2159 non-null   float64
dtypes: datetime64[ns](1), float64(1), int64(2), object(3)
memory usage: 134.9+ KB

In [261]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1112 entries, 0 to 1111
Data columns (total 7 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   ActivitySiteID       1112 non-null   object
 1   ActivityDescription  1112 non-null   object
 2   BookingEndDateTime   1112 non-null   datetime64[ns]
 3   BookingStartTime     1112 non-null   object
 4   MaxBookees           1112 non-null   int64
 5   Number Booked        1112 non-null   int64
 6   PriceINR             1112 non-null   int64
dtypes: datetime64[ns](1), int64(3), object(3)
memory usage: 60.9+ KB

In [262]:
# Correct data types
df1['MaxBookees'] = df1['MaxBookees'].astype(int)
df1['Number Booked'] = df1['Number Booked'].astype(int)
df1['PriceINR'] = pd.to_numeric(df1['PriceINR'].astype(int), errors='coerce')
df2['MaxBookees'] = df2['MaxBookees'].astype(int)
df2['Number Booked'] = df2['Number Booked'].astype(int)
df2['PriceINR'] = pd.to_numeric(df2['PriceINR'], errors='coerce')

In [263]:
# Merge datasets using a common key (e.g., Class ID, Studio ID).
df_merged = pd.concat([df1, df2], ignore_index=True)
df_merged

,ActivitySiteID,ActivityDescription,BookingEndDateTime,BookingStartTime,MaxBookees,Number Booked,PriceINR
0,HXP,20-20-20 2.45pm-3.45pm,2018-04-08,14:45:00,25,12,499
1,HXP,20-20-20 2.45pm-3.45pm,2018-04-15,14:45:00,25,15,499
2,HXP,20-20-20 2.45pm-3.45pm,2018-04-22,14:45:00,25,14,499
3,HXP,20-20-20 2.45pm-3.45pm,2018-04-29,14:45:00,25,9,499
4,HXP,20-20-20 2.45pm-3.45pm,2018-05-06,14:45:00,25,7,499
...,...,...,...,...,...,...,...
3266,TSC,Zumba 6.30-7.30pm,2018-06-18,18:30:00,18,9,1299
3267,TSC,Zumba 6.30-7.30pm,2018-06-25,18:30:00,18,9,1299
3268,TSC,Zumba - 6-7pm,2018-06-07,18:00:00,50,16,1299
3269,TSC,Zumba - 6-7pm,2018-06-14,18:00:00,50,13,1299
3270,TSC,Zumba - 6-7pm,2018-06-21,18:00:00,50,12,1299

In [264]:
df_merged['ActivityDescription'] = df_merged['ActivityDescription'].astype(str).str.strip().str.lower()
df_merged

,ActivitySiteID,ActivityDescription,BookingEndDateTime,BookingStartTime,MaxBookees,Number Booked,PriceINR
0,HXP,20-20-20 2.45pm-3.45pm,2018-04-08,14:45:00,25,12,499
1,HXP,20-20-20 2.45pm-3.45pm,2018-04-15,14:45:00,25,15,499
2,HXP,20-20-20 2.45pm-3.45pm,2018-04-22,14:45:00,25,14,499
3,HXP,20-20-20 2.45pm-3.45pm,2018-04-29,14:45:00,25,9,499
4,HXP,20-20-20 2.45pm-3.45pm,2018-05-06,14:45:00,25,7,499
...,...,...,...,...,...,...,...
3266,TSC,zumba 6.30-7.30pm,2018-06-18,18:30:00,18,9,1299
3267,TSC,zumba 6.30-7.30pm,2018-06-25,18:30:00,18,9,1299
3268,TSC,zumba - 6-7pm,2018-06-07,18:00:00,50,16,1299
3269,TSC,zumba - 6-7pm,2018-06-14,18:00:00,50,13,1299
3270,TSC,zumba - 6-7pm,2018-06-21,18:00:00,50,12,1299

In [265]:
df_merged.isnull().sum()

ActivitySiteID         0
ActivityDescription    0
BookingEndDateTime     0
BookingStartTime       0
MaxBookees             0
Number Booked          0
PriceINR               0
dtype: int64

In [266]:
# Extract hour from BookingStartTime
df_merged['Hour'] = pd.to_numeric(df_merged['BookingStartTime'].str.extract(r'^(\d{1,2}):', expand=False), errors='coerce')

In [267]:
# Extract date components for time series analysis
df_merged['Month'] = df_merged['BookingEndDateTime'].dt.month
df_merged['Week'] = df_merged['BookingEndDateTime'].dt.isocalendar().week
df_merged['DayOfWeek'] = df_merged['BookingEndDateTime'].dt.day_name()
df_merged['DayOfWeekNum'] = df_merged['BookingEndDateTime'].dt.dayofweek

In [268]:
# Occupancy rate
df_merged['occupancy_rate'] = df_merged['Number Booked'] / df_merged['MaxBookees']
df_merged['occupancy_rate'] = df_merged['occupancy_rate']
df_merged

,ActivitySiteID,ActivityDescription,BookingEndDateTime,BookingStartTime,MaxBookees,Number Booked,PriceINR,Hour,Month,Week,DayOfWeek,DayOfWeekNum,occupancy_rate
0,HXP,20-20-20 2.45pm-3.45pm,2018-04-08,14:45:00,25,12,499,14,4,14,Sunday,6,0.48
1,HXP,20-20-20 2.45pm-3.45pm,2018-04-15,14:45:00,25,15,499,14,4,15,Sunday,6,0.60
2,HXP,20-20-20 2.45pm-3.45pm,2018-04-22,14:45:00,25,14,499,14,4,16,Sunday,6,0.56
3,HXP,20-20-20 2.45pm-3.45pm,2018-04-29,14:45:00,25,9,499,14,4,17,Sunday,6,0.36
4,HXP,20-20-20 2.45pm-3.45pm,2018-05-06,14:45:00,25,7,499,14,5,18,Sunday,6,0.28
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3266,TSC,zumba 6.30-7.30pm,2018-06-18,18:30:00,18,9,1299,18,6,25,Monday,0,0.50
3267,TSC,zumba 6.30-7.30pm,2018-06-25,18:30:00,18,9,1299,18,6,26,Monday,0,0.50
3268,TSC,zumba - 6-7pm,2018-06-07,18:00:00,50,16,1299,18,6,23,Thursday,3,0.32
3269,TSC,zumba - 6-7pm,2018-06-14,18:00:00,50,13,1299,18,6,24,Thursday,3,0.26
3270,TSC,zumba - 6-7pm,2018-06-21,18:00:00,50,12,1299,18,6,25,Thursday,3,0.24

In [269]:
# QA checks
miss = df_merged.isna().mean().sort_values(ascending=False).reset_index()
miss.columns = ['column','fraction_missing']
dup_count = df_merged.duplicated().sum()
mixed_types = {c: df_merged[c].dropna().apply(lambda x: type(x)).value_counts().to_dict() for c in df_merged.columns if df_merged[c].dropna().apply(lambda x: type(x)).nunique() > 1}
num_stats = {c: {"count": int(df_merged[c].count()), "min": float(df_merged[c].min()), "max": float(df_merged[c].max()), "mean": float(df_merged[c].mean()), "std": float(df_merged[c].std())} for c in df_merged.select_dtypes(include=[np.number]).columns}
print("="*80)
print("Checking for any missing values in column =", miss)
print("="*80)
print("Checking for duplicate rows =", dup_count)
print("="*80)
num_stats_df = pd.DataFrame(num_stats).T.reset_index()
num_stats_df

================================================================================
Checking for any missing values in column =                  column  fraction_missing
0        ActivitySiteID               0.0
1   ActivityDescription               0.0
2    BookingEndDateTime               0.0
3      BookingStartTime               0.0
4            MaxBookees               0.0
5         Number Booked               0.0
6              PriceINR               0.0
7                  Hour               0.0
8                 Month               0.0
9                  Week               0.0
10            DayOfWeek               0.0
11         DayOfWeekNum               0.0
12       occupancy_rate               0.0
================================================================================
Checking for duplicate rows = 0
================================================================================

            index   count         min          max         mean         std
0      MaxBookees  3271.0    2.000000    70.000000    32.224396   15.121398
1   Number Booked  3271.0    1.000000    64.000000    17.125955    9.515352
2        PriceINR  3271.0  499.000000  3999.000000  1852.714460  792.636673
3            Hour  3271.0    6.000000    20.000000    13.370223    3.920957
4           Month  3271.0    4.000000     6.000000     5.013452    0.816386
5            Week  3271.0   13.000000    26.000000    20.006114    3.759346
6    DayOfWeekNum  3271.0    0.000000     6.000000     2.416081    1.735818
7  occupancy_rate  3271.0    0.016667     5.166667     0.572330    0.319064

In [270]:
# Normalize numerical features
scaler = StandardScaler()
num_cols = ['Number Booked', 'MaxBookees', 'PriceINR']
df_merged[num_cols] = scaler.fit_transform(df_merged[num_cols]).round(2)
df_merged

,ActivitySiteID,ActivityDescription,BookingEndDateTime,BookingStartTime,MaxBookees,Number Booked,PriceINR,Hour,Month,Week,DayOfWeek,DayOfWeekNum,occupancy_rate
0,HXP,20-20-20 2.45pm-3.45pm,2018-04-08,14:45:00,-0.48,-0.54,-1.71,14,4,14,Sunday,6,0.48
1,HXP,20-20-20 2.45pm-3.45pm,2018-04-15,14:45:00,-0.48,-0.22,-1.71,14,4,15,Sunday,6,0.60
2,HXP,20-20-20 2.45pm-3.45pm,2018-04-22,14:45:00,-0.48,-0.33,-1.71,14,4,16,Sunday,6,0.56
3,HXP,20-20-20 2.45pm-3.45pm,2018-04-29,14:45:00,-0.48,-0.85,-1.71,14,4,17,Sunday,6,0.36
4,HXP,20-20-20 2.45pm-3.45pm,2018-05-06,14:45:00,-0.48,-1.06,-1.71,14,5,18,Sunday,6,0.28
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3266,TSC,zumba 6.30-7.30pm,2018-06-18,18:30:00,-0.94,-0.85,-0.70,18,6,25,Monday,0,0.50
3267,TSC,zumba 6.30-7.30pm,2018-06-25,18:30:00,-0.94,-0.85,-0.70,18,6,26,Monday,0,0.50
3268,TSC,zumba - 6-7pm,2018-06-07,18:00:00,1.18,-0.12,-0.70,18,6,23,Thursday,3,0.32
3269,TSC,zumba - 6-7pm,2018-06-14,18:00:00,1.18,-0.43,-0.70,18,6,24,Thursday,3,0.26
3270,TSC,zumba - 6-7pm,2018-06-21,18:00:00,1.18,-0.54,-0.70,18,6,25,Thursday,3,0.24

In [271]:
# cleaning actions
cleaned = df_merged.copy()
all_null_cols = [c for c in cleaned.columns if cleaned[c].isna().all()]
cleaned = cleaned.drop(columns=all_null_cols)
cleaned = cleaned.drop_duplicates().reset_index(drop=True)

In [272]:
DATA_DIR = Path('.') # Define DATA_DIR as the current directory

# save
cleaned.to_excel(DATA_DIR / "cleaned_dataset.xlsx", index=False)
cleaned.to_csv(DATA_DIR / "cleaned_dataset.csv", index=False)